---
title: "关于试验设计" 
subtitle: "" 
author: ""
date: "丁记科技，2025年11月6日"
output: 
  html_document: 
    classoption: “hyperref”
    fig_caption: yes
    fig_height: 4.5
    highlight: tango
    number_sections: no
    theme: cosmo
    toc: no
    toc_depth: 5
    toc_float: yes
---


<style type="text/css">
	#header {
	    text-align: center;        #使得题目居中。借鉴！
	}

	/*备注*/
	/*备注*/
	/*备注*/
	/*备注*/
	/*备注*/
	
	/*为了嵌套列表，需要就地格式，否则3级有序的符号等于1级有序例如一、；*/
	
	/*整个列表趋于可以叠加格式，包括间隙大小、需要随符号调整，例如繁体数字则须加大空隙：https://www.w3school.com.cn/tiy/t.asp?f=css_list-style-red-border；https://www.w3school.com.cn/tiy/t.asp?f=css_list-style-border；https://www.w3school.com.cn/css/css_list.asp或https://www.w3school.com.cn/tiy/t.asp?f=css_list-style_colors背景颜色、间隙等*/
	/*不同列表符号的设置和调用：outside和inside有用；https://www.w3school.com.cn/tiy/t.asp?f=css_list-style-position#google_vignette；https://www.w3school.com.cn/tiy/t.asp?f=css_list-style-type_all#google_vignette；*/
	/*列表符号以图片https://www.w3school.com.cn/tiy/t.asp?f=css_list-style-image*/
	/*？列表：缩进：减小之：！！！！！！！！！！！！！！！！*/
	/*？列表：三级：！！！！！！！！！！！！！！！！*/

  ul {list-style-type:disc;outside;
  margin-top: 1em;
  margin-bottom: 1 em;
  margin-left: 0;
  margin-right: 0;
  padding-left: 40px;	/*默认40*/
  } 	
	/*列表：符号：disc实心圆、默认;square实心正方形;circle空心圆;none（错误的nohe会变为数字而非取消！！！*/
	/*自定义符号，例如"\1F44D"，然则，改为"\261B"：要给出空格，&nbsp;两个即可*/
	/*space-counter;何指？*/
	/*参见https://developer.mozilla.org/zh-CN/docs/Web/CSS/list-style-type、list-style-type - CSS：层叠样式表 _ MDN.html*/

  ul ul { list-style: "\261B &nbsp; &nbsp;"; outside } 	
  	/*设置为手势"\261B &nbsp; &nbsp;"*/
  	/*更多符号，参见https://developer.mozilla.org/zh-CN/docs/Web/CSS/list-style-type、list-style-type - CSS：层叠样式表 _ MDN,！！！，例如，simp-chinese-informal，则自动一、二、等，simp-chinese-formal则壹、但是不可拷贝，尽管不是ol、有序列表，，！！！！！*/

  ul ul  ul { list-style: square ;inside } 	
  /*三级列表：打勾"\2714 &nbsp; &nbsp;" ■square；*/

  /*二级列表：可以自定义：例如：square改为"\261B &nbsp; &nbsp;"：手势符号：！！！*/
  /*加大空格，否则默认没有*/
  /*或者2726较好.较好、2756较好.较好、25C6较好.较好、22C6太小 、2605太突出 、2724较好.不佳、2731太突出、2736较好.不佳、273D较好.不佳*/
  /*Any UL child of a UL，参见https://drafts.csswg.org/css-lists/#list-style-property，！！！位置者，例如outside，意义和举例参见list-style-position - CSS：层叠样式表 _ MDN.html*/
  /* 如果outside，则符号突出在外面；如果inside则缩进加大，inside较好；为什么没有变化？*/
	/*二级列表：问题：似乎因电脑而异：？似乎不是，应该足够空格和不要空行！！！*/

  ol {list-style-type:simp-chinese-informal;}
/*有序列表的编号：数字decimal；小写罗马数字lower-roman;大写罗马数字upper-roman;大写字母upper-alpha；小写字母lower-alpha；似乎无效？非也，1.和a.即可分别自动编号！但A.不行，另外，simp-chinese-informal之，则<ol>会一、但1.仍然1、；*/

  ol ol {list-style-type:lower-roman;}

/* 链接的设置，似乎无效？参见https://www.w3school.com.cn/tiy/t.asp?f=css_link_1 、https://www.w3school.com.cn/css/css_link.asp 更多设置、*/
/* unvisited link */
a:link {
  color: crimson;
}

/* visited link */
a:visited {
  color: blue;
}

/* mouse over link */
a:hover {
  color: red;
}

/* selected link */
a:active {
  color: hotpink;
}

/*横线1：灰色（定稿=灰色DimGray，DarkOliveGreen临时之用！！！）*/
/*接近灰色之备选：DarkOliveGreen、SaddleBrown、SteelBlue*/
/*细线1px，先粗线2px*/
/*调用:<hr class="px1">*/
hr.px1 { 
	height:2px;  
  border-width:0;
  color:DarkOliveGreen;
  background-color:DarkOliveGreen;
  align:left;
  width:100%;
  } 
  
	/*横线2：红色Crimson、粗线2px；调用：<hr class="px2">*/
	hr.px2 { 
	height:50px;  
  border-width:0;
  color:rosybrown;
  background-color:rosybrown;
  align:left;
  width:100%;
  } 
  
  /*横线：whitesmoke、细线1px；调用<hr class="whitesmoke">，先粗线2px*/
	hr.whitesmoke { 
	height:2px;  
  border-width:0;
  color:whitesmoke;
  background-color:whitesmoke;
  align:left;
  width:100%;
  } 
  
	/*横线：居中：灰色：细线1px；调用<hr class="Centered">，先粗线2px*/
	hr.Centered { 
	height:2px;  
  border-width:0;
  color:grey;
  background-color:grey;
  align:center;
  width:60%;
  } 
  
	/*横线：绿色、细线1px；调用<hr class="darkgreen">，先粗线2px*/
	hr.darkgreen { 
	height:2px;  
  border-width:0;
  color:darkgreen;
  background-color:darkgreen;
  align:left;
  width:100%;
  } 
  
	aside {
  width: 30%;
  padding-left: 15px;
  margin-left: 15px;
  float: right;
  /*CSS的备注方式：font-style: italic;*/
  background-color: lightgray;
}

p.large {
  font-size: 200%;
}

p.center {
  text-align: center;
  color: crimson;
}

/*备注：背景、Fill，可以大段文字、列表等，不必换行符，注意字号11px；*/
/*颜色：草稿=绿色：SeaGreen；定稿=灰色DimGray(考虑到Fill中表格文字的颜色，该颜色最佳！！！，另外，横线也要以该颜色！！！即，替换hr class="px1"处的颜色，！！！)、略深：#2F4F4F和darkslategrey：不佳、怪异；蓝色SteelBlue：不佳、怪异；Navy：作为文字仍然太亮；*/
/*颜色等格式：打印还是没有用：？*/
/*边框颜色：border-color:black;似乎无用：？？？*/

div.Gainsboro { font-family: "Cambria","Helvetica Neue", "Segoe UI",Tahoma, arial, helvetica, "PingFang SC", "Hiragino Sans GB", "Heiti SC", "Microsoft YaHei", "WenQuanYi Micro Hei";sans-serif;simsun; background-color:Gainsboro; color:SeaGreen; border-radius: 9px; padding: 9px;font-size: 10px;}

/*-------------------------------------------------------------------------*/

/*表格的文字颜色：默认是黑色，能否通过div进行设置：没有用？？？*/
/*styled-table还是table，？？？*/
/*调用是<div class = "table"></div><br>：没有用？？？*/
/*备选方案：修改源代码，检索以“是过程能力的一种表征”等内容；*/
/*备选方案：偷懒，不修改；*/
div.table { class="styled-table";font-family: "Cambria","Helvetica Neue", "Segoe UI",Tahoma, arial, helvetica, "PingFang SC", "Hiragino Sans GB", "Heiti SC", "Microsoft YaHei", "WenQuanYi Micro Hei";sans-serif;simsun; background-color:Gainsboro; color:SeaGreen; border-radius: 9px; padding: 9px;font-size: 10px;}


/*多重dvi：可以嵌套，见下代码备注掉者：div class = "navy"处；*/
div.navy { font-family: "Cambria","Helvetica Neue", "Segoe UI",Tahoma, arial, helvetica, "PingFang SC", "Hiragino Sans GB", "Heiti SC", "Microsoft YaHei", "WenQuanYi Micro Hei";sans-serif;simsun; background-color:white; color:blue; border-radius: 9px; padding: 9px;font-size: 10px;}


/*多重dvi：表格：没有用：因为R的表格相当于进行了局部div，参见源代码！！！；*/
/*但是似乎可以解决：参见：knitr.Package vignettes.表格等可以调用外部CSS，！！！！html，然则，设置并调用CSS即可，不必担心格式细节，一劳永逸即可！！！*/
/*另外，见下代码之：opts <- options(knitr.kable.NA = "")或许可以解决；！！！；*/

div.Filled.Table { 

table, th, td {
  border: SeaGreen;
}

table {
  background-color: white;
  }

th {
  background-color: gold;
  color: blue;}
}

/*所以，应该修改源代码，*/

/*-------------------------------------------------------------------------*/

/*备注：替代横线：调用是<div class = "DarkGreen"></div><br>，还可以文字、白色等；*/
div.DarkGreen { background-color:DarkGreen; color:white; border-radius: 0px; padding: 1px;font-size: 18px;text-align: center;}

/*-------------------------------------------------------------------------*/

<font-family='"Cambria","Helvetica Neue", "Segoe UI",Tahoma, arial, helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei",sans-serif' size=2> 

/*避免使用font-face不用，改为font-family，以免字体侵权；*/
/*<font face='"Cambria","Helvetica Neue", "Segoe UI",Tahoma, arial, helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei",sans-serif' size=2> */
/*尝试先用思源黑体："Noto Sans SC",*/
/*Noto Sans SC Black似乎无用*/
/*此处似乎无用：前面有其他设置：？？？*/
/*参见源代码检索font-face的结果，请供应商解决，必须避免侵权方式调用字体！！！；*/


/*-------------------------------------------------------------------------*/

</style>


<font face='"Cambria","Helvetica Neue", "Segoe UI",Tahoma, arial, helvetica, "PingFang SC", 
"Hiragino Sans GB", "Microsoft YaHei",sans-serif' size=2> 

```{r  include=FALSE }              
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,background="red") 
#先命令行处setwd("F:/DOE/MK.Rmd/MK.Rmd.D.RPD")，否则，不同电脑盘符不同，可能有问题；
```

\

我们先看看什么是试验设计、为什么要进行试验设计。


<p style="background-color:navy;color:white; border-radius: 30px;text-align:center"><font size=3><b>
试验设计是什么</b></font>
</p>

试验设计，或者实验设计，是指对如下诸多要素的安排：

- 研究目的
- 预期结论
- 响应
- 因子
- 分析测试
- 数据分析方法
- 试验的数量、次序、时间、地点
- 人员、设备、材料、环境，等等


</font>

\
\

